version: '3'
services:
  

  balanceode-api:
    build: ./Balanceode-api/
    networks:
      - quiznet
    ports:
      - "8000:80"
    depends_on:
      - serverapi1
      - serverapi2

  
  balanceode-app:
    build: ./Balanceode-app/
    networks:
      - quiznet
    ports:
      - "2000:80"
    depends_on:
      - 1ercliente
      - 2docliente

  server-api1: 
    build: ./todo-api/
    networks:
      - quiznet
    ports:
      - "8001:8000"
    environment:
      SERVER_TAG: "servicio1-api"
      DATABASE_SERVER: "sqlserver"
      DATABASE_AUTHENTICATION_TYPE: "default"
      DATABASE_AUTHENTICATION_USERNAME: "sa"
      DATABASE_AUTHENTICATION_PASSWORD: "Ariel02"
      DATABASE_OPTION_DATABASE: "todosDB"

  serverapi2: 
    build: ./todo-api/
    networks:
      - quiznet
    ports:
      - "8002:8000"
    environment:
      SERVER_TAG: "servicio2-api"
      DATABASE_SERVER: "sqlserver"
      DATABASE_AUTHENTICATION_TYPE: "default"
      DATABASE_AUTHENTICATION_USERNAME: "sa"
      DATABASE_AUTHENTICATION_PASSWORD: "Ariel02"
      DATABASE_OPTION_DATABASE: "todosDB"
 
      
    depends_on:
      - DB
   
  1ercliente:
    build: 
      context: ./todo-app/
      args:
        - API_HOST="http://localhost:8000/api/todos"
    networks:
      - quiznet
    ports:
      - "2001:80"
    depends_on:
      - DB

  2docliente:
    build: 
      context: ./todo-app/
      args:
        - API_HOST="http://localhost:8000/api/todos"
    networks:
      - quiznet
    ports:
      - "2002:80"
    depends_on:
      - DB

  DB:
    image: "mcr.microsoft.com/mssql/server"
    hostname: "sqlserver"
    networks:
      - quiznet
    volumes:
      - quizdata:/var/opt/mssql/
    environment:
      SA_PASSWORD: "Ariel02"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"


networks:
  quiznet:
    driver: bridge

volumes:
  quizdata:
